// import localFont from "next/font/local";
import "./globals.css";
import {Inter, Josefin_Sans} from 'next/font/google'

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const inter = Inter({
  display: "swap",
  subsets: ['latin']
});

const josefinSans = Josefin_Sans({
  display: "swap",
  subsets: ['latin']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html>
      <body
        className={`bg-background ${inter}`}
      >
        {children}
      </body>
    </html>
  );
}
